server:
  port: 9000

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/order-hub?ssl=false&stringtype=unspecified
    username: ${DB_USERNAME}
    password: ${DB_PWD}
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20

management:
  endpoint:
    health:
      enabled: false
