server:
  port: 9000

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PWD}
    url: jdbc:p6spy:mysql://${DB_HOST}:${DB_PORT}/dis-fb
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20

management:
  endpoint:
    health:
      enabled: false
